/**
 * ArtisanConnect - Central Database of Artisans
 */

const artisans = [
    {
        id: '1',
        name: 'Marc Dubois',
        job: 'Plombier Chauffagiste',
        avatar: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
        location: 'Cotonou',
        price: 20000,
        priceText: '20 000F / hr',
        rating: 4.9,
        reviews: 128,
        about: "Bonjour ! Je suis Marc, plombier chauffagiste passionné. Avec plus de 8 ans d'expérience, j'interviens rapidement pour tous vos dépannages d'urgence.",
        category: 'Plomberie',
        tag: 'Dispo demain',
        verified: true,
        seed: 'plumber1'
    },
    {
        id: '2',
        name: 'Sarah K.',
        job: 'Électricienne',
        avatar: 'https://images.unsplash.com/photo-1601599561096-f87c95fff1e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Akpakpa, Cotonou',
        price: 0, // Sur Devis
        priceText: 'Sur Devis',
        rating: 4.4,
        reviews: 94,
        about: "Électricienne qualifiée avec 5 ans d'expérience. Spécialisée dans la remise aux normes électriques et la domotique.",
        category: 'Électricité',
        tag: 'Dispo',
        verified: true,
        seed: 'elec1'
    },
    {
        id: '3',
        name: 'Atelier Boni',
        job: 'Menuiserie',
        avatar: 'assets/carpentry_img.png',
        location: 'Godomey',
        price: 0,
        priceText: 'Sur Devis',
        rating: 5.0,
        reviews: 45,
        about: "L'art du bois est notre passion depuis 15 ans. Meubles sur mesure, dressings et charpentes.",
        category: 'Menuiserie',
        tag: 'Ouvert',
        verified: true,
        seed: 'menuiserie1'
    },
    {
        id: '4',
        name: 'Jean Peintre',
        job: 'Peinture',
        avatar: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Fidjrossè',
        price: 15000,
        priceText: '15 000F / hr',
        rating: 4.5,
        reviews: 67,
        about: "Artisan peintre expérimenté. Finitions soignées et peintures écologiques résistantes.",
        category: 'Peinture',
        tag: "Aujourd'hui",
        verified: false,
        seed: 'peintre1'
    },
    {
        id: '5',
        name: 'Paul L. Dépannage',
        job: 'Débouchage & Réparation',
        avatar: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Calavi',
        price: 0,
        priceText: 'Sur Devis',
        rating: 4.5,
        reviews: 32,
        about: "Expert en dépannage d'urgence et en débouchage d'installations avec 12 ans de métier.",
        category: 'Plomberie',
        tag: 'Dispo en 48h',
        verified: false,
        seed: 'plumber2'
    },
    {
        id: '6',
        name: 'Société Eaux & Co',
        job: 'Installation Sanitaire',
        avatar: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Akpakpa',
        price: 15000,
        priceText: '15 000F / hr',
        rating: 4.8,
        reviews: 89,
        about: "Société spécialisée dans les installations sanitaires complexes. Garanties pièces et main-d'œuvre.",
        category: 'Plomberie',
        tag: 'Urgence 24/7',
        verified: true,
        seed: 'plumber3'
    },
    {
        id: '7',
        name: 'Bâtisseurs Sûrs',
        job: 'Maçon',
        avatar: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Cotonou (Haie Vive)',
        price: 0,
        priceText: 'Sur Devis',
        rating: 4.7,
        reviews: 56,
        about: "Experts en maçonnerie générale, fondations solides et grand souci du détail.",
        category: 'Maçonnerie',
        tag: 'Dispo',
        verified: true,
        seed: 'macon2'
    },
    {
        id: '8',
        name: 'Koffi Design',
        job: 'Carreleur',
        avatar: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Akpakpa',
        price: 3000,
        priceText: '3 000F / m2',
        rating: 4.6,
        reviews: 41,
        about: "Pose de tous types de revêtements de sol ou de mur. Mosaïques, faïences, marbre.",
        category: 'Carrelage',
        tag: 'En mission',
        verified: false,
        seed: 'carreleur2'
    },
    {
        id: '9',
        name: 'Plafonds Modernes',
        job: 'Poseur de faux-plafond',
        avatar: 'assets/plafond_img.png',
        location: 'Godomey',
        price: 0,
        priceText: 'Sur Devis',
        rating: 4.8,
        reviews: 24,
        about: "Spécialisée dans les faux-plafonds suspendus, tendus ou en plâtre.",
        category: 'Faux-plafond',
        tag: 'Dispo demain',
        verified: false,
        seed: 'plafond2'
    },
    {
        id: '10',
        name: 'Climatisation Plus',
        job: 'Technicien clim / froid',
        avatar: 'assets/clim_img.png',
        location: 'Cotonou (Gbégamey)',
        price: 10000,
        priceText: '10 000F / hr',
        rating: 5.0,
        reviews: 15,
        about: "Réparation de tous types de chambres froides ou climatiseurs, entretien régulier.",
        category: 'Climatisation',
        tag: 'Dispo ce soir',
        verified: true,
        seed: 'clim2'
    },
    {
        id: '11',
        name: 'Auto-Élec Pro',
        job: 'Électricien auto / moto',
        avatar: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Fidjrossè',
        price: 7000,
        priceText: '7 000F / panne',
        rating: 4.4,
        reviews: 37,
        about: "Intervention rapide pour les soucis électriques sur votre véhicule à 2 ou 4 roues.",
        category: 'Électricité Auto',
        tag: 'Rapide',
        verified: false,
        seed: 'elecauto2'
    },
    {
        id: '12',
        name: 'Fer & Forge',
        job: 'Soudeur / Ferronnier',
        avatar: 'assets/soudeur_img.png',
        location: 'Calavi (Kpota)',
        price: 0,
        priceText: 'Sur Devis',
        rating: 4.9,
        reviews: 18,
        about: "Portails, fenêtres, ou balcons en fer forgé avec de belles finitions artistiques.",
        category: 'Soudure',
        tag: 'L-V',
        verified: false,
        seed: 'soudeur2'
    },
    {
        id: '13',
        name: 'Couture Édition',
        job: 'Couturier / Tailleur',
        avatar: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Maro-Militaire',
        price: 0,
        priceText: 'Sur Modèle',
        rating: 5.0,
        reviews: 82,
        about: "Création sur mesure d'ensembles tailleur, robes de soirées ou tenues traditionnelles.",
        category: 'Couture',
        tag: 'Dispo',
        verified: true,
        seed: 'couture2'
    },
    {
        id: '14',
        name: 'Salon Beauté',
        job: 'Coiffeur / Coiffeuse',
        avatar: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Saint-Michel',
        price: 2000,
        priceText: 'Dès 2 000F',
        rating: 4.8,
        reviews: 105,
        about: "Tresses, défrisages, ou simples coupes d'entretien avec massage crânien.",
        category: 'Coiffure',
        tag: 'Sans rdv',
        verified: false,
        seed: 'coiffeur2'
    },
    {
        id: '15',
        name: 'Garage Central',
        job: 'Mécanicien auto / moto',
        avatar: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Agla',
        price: 5000,
        priceText: 'Diagnosis: 5 000F',
        rating: 4.6,
        reviews: 56,
        about: "Spécialiste de la réparation automobile, de l'entretien à la mécanique lourde.",
        category: 'Mécanique',
        tag: 'Ouvert',
        verified: true,
        seed: 'meca2'
    },
    {
        id: '16',
        name: 'Pneus Rapides',
        job: 'Vulcanisateur',
        avatar: 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Étoile Rouge',
        price: 500,
        priceText: '500F / Patch',
        rating: 4.5,
        reviews: 31,
        about: "Colmatage, réparation et regonflage de toute roue 24h sur 24.",
        category: 'Vulcanisateur',
        tag: 'Urgences 24/7',
        verified: false,
        seed: 'pneu2'
    },
    {
        id: '17',
        name: 'Mobile Doc',
        job: 'Réparateur téléphone',
        avatar: 'assets/phone_img.png',
        location: 'Gbégamey',
        price: 0,
        priceText: 'Devis',
        rating: 4.9,
        reviews: 89,
        about: "Experts iPhone, Android. Remplacement d'écrans, batteries et récupération de données.",
        category: 'Téléphone',
        tag: 'Dispo',
        verified: true,
        seed: 'tel2'
    },
    {
        id: '18',
        name: 'Élec-Rapide',
        job: 'Électricien',
        avatar: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Cotonou',
        price: 10000,
        priceText: '10 000F / hr',
        rating: 4.7,
        reviews: 12,
        about: "Dépannage rapide toutes pannes électriques, mise aux normes et raccordements.",
        category: 'Électricité',
        tag: 'Dispo',
        verified: false,
        seed: 'elec2'
    },
    {
        id: '19',
        name: 'Bois de Rêve',
        job: 'Menuiserie',
        avatar: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Calavi',
        price: 0,
        priceText: 'Sur Devis',
        rating: 4.7,
        reviews: 28,
        about: "Création de meubles sur demande, aménagements intérieurs et placards sur mesure.",
        category: 'Menuiserie',
        tag: 'En semaine',
        verified: false,
        seed: 'menuiserie2'
    },
    {
        id: '20',
        name: 'Couleurs Magiques',
        job: 'Peinture',
        avatar: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        location: 'Agla',
        price: 5000,
        priceText: '5 000F / m2',
        rating: 4.7,
        reviews: 15,
        about: "Peinture bâtiment et décoration intérieure, devis rapide et travail soigné.",
        category: 'Peinture',
        tag: 'Sur rdv',
        verified: false,
        seed: 'peintre2'
    },
    {
        id: '21',
        name: 'Propre Vite',
        job: 'Nettoyage',
        avatar: 'https://ui-avatars.com/api/?name=Propre+Vite&size=400&background=random',
        location: 'Cotonou (Haie Vive)',
        price: 10000,
        priceText: 'Dès 10 000F',
        rating: 4.6,
        reviews: 50,
        about: "Nettoyage et entretien de bureaux, remise en état après chantier.",
        category: 'Nettoyage',
        tag: 'Dispo',
        verified: true,
        seed: 'nettoyage1'
    }
];

// Map for quick lookup by ID
const artisansData = {};
artisans.forEach(a => {
    artisansData[a.id] = {
        name: a.name,
        job: a.job,
        avatar: a.avatar,
        location: `Intervient : ${a.location}`,
        price: a.priceText,
        about: a.about,
        rating: a.rating,
        reviews: a.reviews,
        category: a.category,
        tag: a.tag,
        verified: a.verified
    };
});

// Export for use in other scripts (if using modules) or just global
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { artisans, artisansData };
} else {
    window.artisans = artisans;
    window.artisansData = artisansData;
}
